### ISSUE TITLE
Snyk fails to find requirements listed in setup.cfg

### ISSUE THREAD

**Issue by IRDonch** [snyk/snyk-python-plugin#147]
- `node -v`: v14.15.0
- `npm -v`: 6.14.8
- `snyk -v`: 1.595.0
- Command run: `snyk test --command=python3 --file=setup.py`

`setup.py` is:

```python
from setuptools import setup
setup()
```

`setup.cfg` is:

```ini
[metadata]
name = foobar
version = 0.1

[options]
install_requires = requests
```

### Expected behaviour

Snyk should discover the Requests dependency and check it for vulnerabilities.

### Actual behaviour

Snyk outputs:

```
No dependencies detected in manifest.
```

### Steps to reproduce

Just run the command listed in the beginning in the project directory.

---

```
2021-05-14T17:27:45.649Z snyk test <ref *1> {
  _: [ [Circular *1] ],
  command: 'python3',
  file: 'setup.py',
  debug: true
}
2021-05-14T17:27:46.820Z snyk:run-test Error running test {
  error: Error: No dependencies detected in manifest.
      at Object.<anonymous> (/tmp/snyk/node_modules/snyk-python-plugin/lib/dependencies/inspect-implementation.ts:135:15)
      at Generator.throw (<anonymous>)
      at rejected (/tmp/snyk/node_modules/tslib/tslib.js:113:69)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
2021-05-14T17:27:46.826Z snyk-test Failed to test 1 projects, errors:
2021-05-14T17:27:46.851Z snyk-test error: FailedToRunTestError: No dependencies detected in manifest.
    at runTest (/tmp/snyk/node_modules/snyk/src/lib/snyk-test/run-test.ts:363:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at test (/tmp/snyk/node_modules/snyk/src/cli/commands/test/index.ts:109:15)
    at runCommand (/tmp/snyk/node_modules/snyk/src/cli/index.ts:56:25)
    at main (/tmp/snyk/node_modules/snyk/src/cli/index.ts:309:11)
Error: 
Testing /tmp/test-proj...

No dependencies detected in manifest.
    at test (/tmp/snyk/node_modules/snyk/src/cli/commands/test/index.ts:257:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runCommand (/tmp/snyk/node_modules/snyk/src/cli/index.ts:56:25)
    at main (/tmp/snyk/node_modules/snyk/src/cli/index.ts:309:11)

2021-05-14T17:27:46.857Z snyk Exit code: 2
2021-05-14T17:27:46.973Z snyk analytics {
  "args": [
    {
      "command": "python3",
      "file": "setup.py",
      "debug": true
    }
  ],
  "command": "bad-command",
  "metadata": {
    "local": true,
    "error-message": "\nTesting /tmp/test-proj...\n\nNo dependencies detected in manifest.",
    "error": "Error: \nTesting /tmp/test-proj...\n\nNo dependencies detected in manifest.\n    at test (/tmp/snyk/node_modules/snyk/src/cli/commands/test/index.ts:257:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at runCommand (/tmp/snyk/node_modules/snyk/src/cli/index.ts:56:25)\n    at main (/tmp/snyk/node_modules/snyk/src/cli/index.ts:309:11)",
    "error-code": 500,
    "command": "test"
  },
  "version": "1.595.0",
  "os": "Linux 4.15",
  "nodeVersion": "v14.15.0",
  "standalone": false,
  "integrationName": "",
  "integrationVersion": "",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "d199243a799f5ece13f6c51a068aef5fcd0b33c8",
  "ci": false,
  "environment": {
    "npmVersion": "6.14.8"
  },
  "durationMs": 842,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        842
      ],
      "total": 842
    }
  }
}
2021-05-14T17:27:46.974Z snyk sending request to: [redacted]
2021-05-14T17:27:46.974Z snyk request body size: 1051
2021-05-14T17:27:46.974Z snyk gzipped request body size: 526
2021-05-14T17:27:46.975Z snyk not using proxy
```

**Comment by OddBloke** [comment]
Current best practices for Python packaging are to use declarative syntax in `setup.cfg` rather than declaring it via code in `setup.py` (which can execute arbitrary Python code whenever package installation occurs). This issue forces Python projects to either (a) not receive scanning from Snyk, or (b) use a dispreferred (and less predictable/secure/etc.) installation method. It'd be great to get it fixed!
