### ISSUE TITLE
snyk cli errors while scanning `Pipfile`: `"AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. `

### ISSUE THREAD

**Issue by fzipi360** [snyk/snyk-python-plugin#228]
- `node -v`:
- `npm -v`:
- `snyk -v`: `1.1237.0`

- Command run: `DEBUG=*snyk* snyk test --target-reference="master"`

### Expected behaviour

Get the expected results.

### Actual behaviour

Fails with an error.

### Steps to reproduce

1. Create `Pipfile` with contents: 
```[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[requires]
python_version = "3.9"
```
3. Do the snyk auth process
4. Run snyk test

---

If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens.

```
❯ DEBUG=*snyk* snyk test --target-reference="master"
  snyk:config dir: /snapshot/project/dist/cli/../.., local: /snapshot/project/config.local.json, secret: /snapshot/project/config.secret.json +0ms
  snyk:config loading from /snapshot/project/dist/cli/../.. {
  "devDeps": false,
  "PRUNE_DEPS_THRESHOLD": 40000,
  "MAX_PATH_COUNT": 1500000,
  "NPM_TREE_SIZE_LIMIT": 6000000,
  "YARN_TREE_SIZE_LIMIT": 6000000,
  "_": [
    "test"
  ],
  "target-reference": "master",
  "$0": "../../../Library/Caches/snyk/snyk-cli/1.1237.0/snyk-macos-arm64",
  "INTERNAL_ORGID": "<the internal orgid>",
  "INTEGRATION_VERSION": "1.1237.0",
  "SYSTEM_HTTP_PROXY": "",
  "SYSTEM_NO_PROXY": "",
  "INTEGRATION_NAME": "CLI_V1_PLUGIN",
  "SYSTEM_HTTPS_PROXY": ""
} +2ms
  snyk test <ref *1> { _: [ [Circular *1] ], 'target-reference': 'master' } +0ms
  snyk:config dir: /snapshot/project/dist/cli../.., local: /snapshot/project/dist/config.local.json, secret: /snapshot/project/dist/config.secret.json +235ms
  snyk:config loading from /snapshot/project/dist/cli../.. {
  "_": [
    "test"
  ],
  "target-reference": "master",
  "$0": "../../../Library/Caches/snyk/snyk-cli/1.1237.0/snyk-macos-arm64",
  "INTERNAL_ORGID": "<the internal orgid>",
  "INTEGRATION_VERSION": "1.1237.0",
  "SYSTEM_HTTP_PROXY": "",
  "SYSTEM_NO_PROXY": "",
  "INTEGRATION_NAME": "CLI_V1_PLUGIN",
  "SYSTEM_HTTPS_PROXY": ""
} +0ms
  snyk-detect no file specified. Trying to autodetect in base folder /Users/...test +0ms
  snyk-detect found package file Pipfile in /Users/...test +0ms
  snyk:spinner spinner: Analyzing pip dependencies for devops-test project dir +0ms
  snyk:spinner creating spinner +0ms
  snyk-detect found package file Pipfile in /Users/...test +1ms
  snyk-module-info calling plugin inspect() {
  root: '/Users/...test',
  targetFile: 'Pipfile',
  pluginOptions: {
    args: undefined,
    _: [ [Object] ],
    'target-reference': 'master',
    org: '<MY ORGH>',
    showVulnPaths: 'some',
    path: '/Users/...test',
    projectName: undefined,
    packageManager: 'pip',
    file: 'Pipfile'
  }
} +0ms
  snyk:spinner clearing Analyzing pip dependencies for devops-test project dir (1) +540ms
  snyk:run-test Error running test {
  error: "/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/pip_resolve.py:168: SyntaxWarning: invalid escape sequence '\\s'\n" +
    '  for sub_exp in re.split("\\s*(?:and|or)\\s*", cond_text):\n' +
    'Traceback (most recent call last):\n' +
    '  File "/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/pip_resolve.py", line 7, in <module>\n' +
    '    import utils\n' +
    '  File "/private/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/utils.py", line 8, in <module>\n' +
    '    from reqPackage import ReqPackage\n' +
    '  File "/private/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/reqPackage.py", line 1, in <module>\n' +
    '    import pkg_resources\n' +
    '  File "/private/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/pkg_resources.py", line 4, in <module>\n' +
    '    from pkg_resources_py3 import *\n' +
    '  File "/private/var/folders/lh/6hhp2t6d3k92r4_jfdh0d8mc0000gp/T/tmp-67151-OQ0bSBCcNOo0/pkg_resources_py3/__init__.py", line 2172, in <module>\n' +
    '    register_finder(pkgutil.ImpImporter, find_on_path)\n' +
    '                    ^^^^^^^^^^^^^^^^^^^\n' +
    "AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?\n"
} +0ms
  snyk-test Failed to test 1 projects, errors: +0ms
  snyk-test error: FailedToRunTestError: Failed to test pip project
    at runTest (/snapshot/project/dist/cli/webpack:/snyk/src/lib/snyk-test/run-test.ts:374:11)
    at test (/snapshot/project/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:155:13)
    at runCommand (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)
    at main (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:310:11)
    at /snapshot/project/dist/cli/webpack:/snyk/src/cli/index.ts:13:3
    at Object.callHandlingUnexpectedErrors (/snapshot/project/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5) +227ms
  snyk:spinner clearing Analyzing pip dependencies for devops-test project dir (0) +229ms
Failed to test pip project
  snyk Exit code: 2 +0ms
  snyk analytics {
  "args": [
    {
      "target-reference": "master"
    }
  ],
  "command": "bad-command",
  "metadata": {
    "upgradable-snyk-protect-paths": 0,
    "local": true,
    "error-message": "\nTesting /Users/...test...\n\nFailed to test pip project",
    "error": "Error: \nTesting /Users/...test...\n\nFailed to test pip project\n    at test (/snapshot/project/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:286:19)\n    at runCommand (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)\n    at main (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:310:11)\n    at /snapshot/project/dist/cli/webpack:/snyk/src/cli/index.ts:13:3\n    at Object.callHandlingUnexpectedErrors (/snapshot/project/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)",
    "error-code": 500,
    "command": "test"
  },
  "os": "macOS",
  "osPlatform": "darwin",
  "osRelease": "23.1.0",
  "osArch": "arm64",
  "version": "1.1237.0",
  "nodeVersion": "v18.5.0",
  "standalone": true,
  "integrationName": "CLI_V1_PLUGIN",
  "integrationVersion": "1.1237.0",
  "integrationEnvironment": "",
  "integrationEnvironmentVersion": "",
  "id": "17552a5089c6caf43751e7fdcddc1007c3bd95ca",
  "ci": false,
  "durationMs": 1148,
  "metrics": {
    "network_time": {
      "type": "timer",
      "values": [],
      "total": 0
    },
    "cpu_time": {
      "type": "synthetic",
      "values": [
        1148
      ],
      "total": 1148
    }
  }
} +0ms
  snyk-metrics Timer timer/network_time started at 1698780708919. +0ms
  snyk:req compressing request body +0ms
  snyk:req {
  snyk:req   "data": {
  snyk:req     "args": [
  snyk:req       {
  snyk:req         "target-reference": "master"
  snyk:req       }
  snyk:req     ],
  snyk:req     "command": "bad-command",
  snyk:req     "metadata": {
  snyk:req       "upgradable-snyk-protect-paths": 0,
  snyk:req       "local": true,
  snyk:req       "error-message": "\nTesting /Users/...test...\n\nFailed to test pip project",
  snyk:req       "error": "Error: \nTesting /Users/...test...\n\nFailed to test pip project\n    at test (/snapshot/project/dist/cli/webpack:/snyk/src/cli/commands/test/index.ts:286:19)\n    at runCommand (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:51:25)\n    at main (/snapshot/project/dist/cli/webpack:/snyk/src/cli/main.ts:310:11)\n    at /snapshot/project/dist/cli/webpack:/snyk/src/cli/index.ts:13:3\n    at Object.callHandlingUnexpectedErrors (/snapshot/project/dist/cli/webpack:/snyk/src/lib/unexpected-error.ts:28:5)",
  snyk:req       "error-code": 500,
  snyk:req       "command": "test"
  snyk:req     },
  snyk:req     "os": "macOS",
  snyk:req     "osPlatform": "darwin",
  snyk:req     "osRelease": "23.1.0",
  snyk:req     "osArch": "arm64",
  snyk:req     "version": "1.1237.0",
  snyk:req     "nodeVersion": "v18.5.0",
  snyk:req     "standalone": true,
  snyk:req     "integrationName": "CLI_V1_PLUGIN",
  snyk:req     "integrationVersion": "1.1237.0",
  snyk:req     "integrationEnvironment": "",
  snyk:req     "integrationEnvironmentVersion": "",
  snyk:req     "id": "<ID>",
  snyk:req     "ci": false,
  snyk:req     "durationMs": 1148,
  snyk:req     "metrics": {
  snyk:req       "network_time": {
  snyk:req         "type": "timer",
  snyk:req         "values": [],
  snyk:req         "total": 0
  snyk:req       },
  snyk:req       "cpu_time": {
  snyk:req         "type": "synthetic",
  snyk:req         "values": [
  snyk:req           1148
  snyk:req         ],
  snyk:req         "total": 1148
  snyk:req       }
  snyk:req     }
  snyk:req   }
  snyk:req } +0ms
  snyk sending request to: https://api.snyk.io/v1/analytics/cli +0ms
  snyk request body size: 1299 +0ms
  snyk gzipped request body size: 613 +0ms
  snyk:req request payload:  {"url":"https://api.snyk.io/v1/analytics/cli","json":true,"method":"post","headers":{"authorization":"token <my token>","x-snyk-cli-version":"1.1237.0","content-encoding":"gzip","content-length":613},"timeout":300000} +1ms
  snyk using proxy: http://snykcli:<some uuid>@127.0.0.1:49164 +1ms
  snyk:req <Buffer 1f 8b 08 00 00 00 00 00 02 13 b5 54 51 6f d3 30 10 fe 2b 95 9f 98 d4 c4 71 b3 b4 5d de d0 34 60 d2 d8 26 60 e3 81 a2 c9 b5 2f ad 59 62 47 f6 a5 5b 99 ... 563 more bytes> +1ms
  snyk:req null +293ms
  snyk:req response (200):  {"ok":true} +0ms
  snyk-metrics Timer timer/network_time stopped at 1698780709215. Elapsed time is 296 +297ms
```

Looks like this happened because `ImpImporter` is deprecated in the `pkgutil` module, and it needs to be switched to `importlib`

**Comment by wwilfinger** [comment]
Any idea on when to expect progress on this? Does snyk-python-plugin really only officially support up to Python 3.9 as stated in the README?

I also wanted to point out the regex syntax warning in the debug output in the OP.

```
pip_resolve.py:168: SyntaxWarning: invalid escape sequence '\\s'\n" +
    '  for sub_exp in re.split("\\s*(?:and|or)\\s*", cond_text):\n'
```

That is [HERE](https://github.com/snyk/snyk-python-plugin/blob/cd240cd/pysrc/pip_resolve.py#L168) in the source. The change to a [SyntaxWarning is new](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes) in Python 3.12.

**Comment by MarcusArdelean** [comment]
@fzipi360 @wwilfinger We just released yesterday support for Python 3.12, the issue should be fixed now. Please let me know if you encounter the same error. Thank you!

**Comment by wwilfinger** [comment]
Looks like that fix did it. I ran my same code against Snyk 1.1264.0 and didn't have any issues. Thanks so much!

**Comment by MarcusArdelean** [comment]
Great, glad to hear that. I will close this issue in that case.
